name: Check project

on:
  push:
    branches: [ "main" ]
  pull_request:

jobs:
  clippy:
    runs-on: ubuntu-24.04

    strategy:
      matrix:
        include:
          - kind: default-features
            features: default
          - kind: full-features
            features: full

    steps:
      - name: Checkout project
        uses: actions/checkout@v3

      - name: Install stable toolchain
        uses: dtolnay/rust-toolchain@stable

      - name: Cache dependencies
        uses: Swatinem/rust-cache@v2

      - name: Add problem matchers
        run: echo "::add-matcher::.github/rust.json"

      - name: Run clippy
        run: cargo clippy --features ${{ matrix.features }} --all-targets

  rustfmt:
    name: Format
    runs-on: ubuntu-24.04

    steps:
      - name: Checkout sources
        uses: actions/checkout@v3

      - name: Install nightly toolchain
        uses: dtolnay/rust-toolchain@stable
        with:
            components: rustfmt
            toolchain: nightly

      - name: Add problem matchers
        run: echo "::add-matcher::.github/rust.json"

      - name: Check code formatting
        run: cargo fmt -- --check